# Generated by Django 2.2.3 on 2019-07-26 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('postdev', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='datetime',
            new_name='created_at',
        ),
    ]
